# jgsys
# (c) 2013 Justin Gottula
# The source code of this project is distributed under the terms of the
# simplified BSD license. See the LICENSE file for details.

TIMESTAMP=$(shell date +'%Y%m%d-%H%M')

AS:=nasm
ASFLAGS:=-fbin -MP -Ox -Wall


.PHONY: all clean backup mbr vbr boot kern

# default rule
all: mbr vbr boot kern

mbr:  bin/mbr
vbr:  bin/vbr
boot: bin/boot
kern: bin/kern

clean:
	rm -rf $(wildcard bin/*) $(wildcard src/*/*.dep)

backup:
	cd .. && tar -acvf jgsys-$(TIMESTAMP).tar.xz jgsys/


# generic binary rule
bin/%: Makefile
	$(AS) $(ASFLAGS) -dMAPFILE=bin/map/$* -o $@ -isrc/ -isrc/$*/ -lbin/lst/$* -MD src/$*/$*.dep src/$*/$*.s


# concatenate nasm's autogenerated dependencies
-include src/*/*.dep
