# jgsys
# (c) 2013 Justin Gottula
# The source code of this project is distributed under the terms of the
# simplified BSD license. See the LICENSE file for details.

TIMESTAMP=$(shell date +'%Y%m%d-%H%M')

AS:=nasm
ASFLAGS:=-fbin -MP -Ox -Wall


.PHONY: all clean backup mbr vbr boot kern

# default rule
all: mbr vbr boot kern

mbr:  out/bin/mbr  out/hex/mbr
vbr:  out/bin/vbr  out/hex/vbr
boot: out/bin/boot out/hex/boot
kern: out/bin/kern out/hex/kern

clean:
	rm -rf $(wildcard out/*/*) $(wildcard src/*/*.dep)

backup:
	cd .. && tar -acvf jgsys-$(TIMESTAMP).tar.xz jgsys/


out/hex/%: out/bin/%
	xxd -a $^ $@

out/bin/%: Makefile
	$(AS) $(ASFLAGS) -dMAPFILE=out/map/$* -o $@ -isrc/ -isrc/$*/ -lout/lst/$* -MD src/$*/$*.dep src/$*/$*.s


# concatenate nasm's autogenerated dependencies
-include src/*/*.dep
