# jgsys
# (c) 2013 Justin Gottula
# The source code of this project is distributed under the terms of the
# simplified BSD license. See the LICENSE file for details.

AS:=nasm
ASFLAGS:=-fbin -MP -Ox -Wall


.PHONY: all clean mbr vbr kern

# default rule
all: mbr vbr kern

mbr:  bin/mbr.bin
vbr:  bin/vbr.bin
kern: bin/kern.bin

clean:
	rm -rf bin/* src/*/*.dep


# generic binary rule
bin/%.386: Makefile
	$(AS) $(ASFLAGS) -o $@ -isrc/$*/ -lbin/$*.lst -MD src/$*/$*.dep src/$*/$*.s


# include nasm's autogenerated dependencies
-include src/*/*.dep
